import { React, useState, useEffect } from "react";
import { Box, Button } from "@mui/material";
import Navbar from "../components/navbar";
import axios from "axios";
import MultiActionAreaCard from "../components/movieCard";
import Head from "next/head";
import Footer from "../components/footer";

function Trending(props) {

  var [movies, setMovies] = useState([]);
  var [ind, setInd] = useState(1);
  var [title, setTitle] = useState("");

  function handleNext() {
    console.log(next);
    setInd(ind + 1);
  }

  function handlePrev() {
    setInd(ind > 1 ? ind - 1 : ind);
  }

  async function getHandle() {
    try {
      const response = await axios.get(
        `https://api.themoviedb.org/3/trending/all/day?api_key=34a470327cec0df094785c27a8b66230&page=${ind}`
      );
      setMovies(response.data.results);
      console.log(response);
    } catch (error) {
      console.log(error.response.status);
    }
  }

  async function searchMovie() {
    try {
      const searchRes = await axios.get(
        `https://api.themoviedb.org/3/search/movie?api_key=34a470327cec0df094785c27a8b66230&language=en-US&query=${title}&include_adult=false`
      );
      setMovies(searchRes.data.results);
    } catch (error) {
      console.log(error.searchRes);
    }
  }

  function handleClick(e){
    e.preventDefault();
    searchMovie();
  }
  function handleChange(e){
    console.log(e.target.value);
    setTitle(e.target.value);
  }

  useEffect(() => {
    getHandle();
  }, [ind]);

  return (
    <>
      <Head>
        <title>Trending</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Box
        sx={{
          height: "20vh",
          width: "100%",
          backgroundImage: `url(./background.jpg)`,
          display: "flex",
          justifyContent: "center",
        }}
      >
        <form >
          <input onChange = {(e) => handleChange(e)} placeholder = "Search Movies..." style={{height: "25%", marginTop: "70px", width: "30vw", borderRadius: "20px", alignItems: "center", paddingLeft: "20px"}} />
          <Button className="search-btn" type="submit" onClick={(e)=>{handleClick(e)}} variant="contained" sx={{height: "25%", borderRadius: "20px", ml: "15px"}}>
            Search
          </Button>
          <i onClick={(e) => handleClick(e)} aria-hidden="true" className="fa fa-search" id="phone"></i>
        </form>
      </Box>

      <Box
        sx={{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "space-evenly",
        }}
      >
        {movies.map((items, index) => {
          return (
            <MultiActionAreaCard
              key={index}
              title={items.title}
              about={items.overview}
              pic={items.poster_path}
              release={items.release_date}
              rating={items.vote_average}
              id = {items.id}
            />
          );
        })}
      </Box>
      <div style={{display: "flex", justifyContent: "flex-start", width: "100%", height: "80px", alignItems: "center", border: "2.5px solid black", borderRadius: "10px", marginTop: "20px", paddingLeft: "5vw", marginRight: "8vw"}}>
        <Button onClick={handlePrev} variant="contained" sx={{ height: "35px", width: "70px", mr: "4vw", backgroundColor: "black" }}>
          Back
        </Button>
        <Button onClick={handleNext} variant="contained" sx={{ height: "35px", width: "70px", backgroundColor: "black" }}>
          Next
        </Button>
      </div>
      {/* <div className="divider"></div> */}
      <Footer />
    </>
  );
}

export default Trending;